### ISSUE TITLE
学习一下

### ISSUE THREAD

**Issue by sdcxzx-tester** [xmgtony/apiserver-gin#20]
简单看了一下,密码是明文传输的,想使用对称加密,有没有推荐一下,最近在学习,没有写的很明白
🐶保命

**Comment by xmgtony** [comment]
对，这里只是演示。其实密码明文传输，在HTTPS模式下一般来说问题不大，实际生产中前面还有网关和反代可以做这些安全校验。
加密也主要解决的是传输过程中的问题。中小项目使用HTTPS协议就行了。
如果使用固定的密钥和固定的加密算法，被人拿到逆向客户端的密钥也容易被破解。建议非对称加密和对称加密配合使用，解释起来比较复杂，请自行google一下哈。

**Comment by sdcxzx-tester** [comment]
好的,感谢
