### ISSUE TITLE
Wire 的写法位置交流

### ISSUE THREAD

**Issue by git2017-jpg** [xmgtony/apiserver-gin#21]
我看项目里面Wire的构造器分散在各个文件里面，是否可以将所有的构建器在cmd 程序 wire.go里面编写，cmd下面可能会有多个入口，在入口的wire里面写对应的构造器是不是会更加灵活一些，业务代码包里面将wire抽离出来。

**Comment by xmgtony** [comment]
也可，这个没有标准和规范，按您自己的项目规划和喜好来即可。
我放在每个对应目录下有以下考虑：
1、就近原则，整体性，比如service包，service的构建器和service本身应该是一个整体，应该由自己管理。不应溢出到其他地方。
2、只导出了接口，外部都是面向接口使用，对应的实现并未导出，拿到外面可能没办法使用。wire生成一个接口时要指定对应的实现和接口绑定。
上面只是我的个人的观点，你可以按照自己的想法来做，根据您的项目需要来规划。在我们的项目中，如果有多个项目，比如cmd下，有管理后台和APP的Api Server。 这两个项目入口，我们是用两个目录来分开的。每个目录下，有自己的main.go和对应的wire.go文件，虽然有一定重复，但也更灵活。
 ─cmd
    ├─admin_server
    ├─api_server
