### ISSUE TITLE
代码分成思考

### ISSUE THREAD

**Issue by onettxx** [xmgtony/apiserver-gin#22]
个人疑问是不是和java的分层差不多?  实体 - 持久层 - 服务层-控制层

**Comment by itshizhan** [comment]
这个项目的确有些java范式。
之前研究过此项目的参考项目，总觉得不够golang

**Comment by xmgtony** [comment]
是的，其实mvc，ddd等等这些，并不是某一门语言独有的，按照约定熟成的模式，可能更容易被接受，没有新概念。内部使用这个作为基础，已经做了大量改进，目前没精力放出，后续整理后放出。
