### ISSUE TITLE
工程化可以参考下kratos最佳实践

### ISSUE THREAD

**Issue by go-worker** [xmgtony/apiserver-gin#23]
1 建议考虑下，工程划分和命名，其实可能和领域的概念理解有关
 2 接口使用其目的是解决依赖，apiseriver-gin这块对接口使用，建议考虑改进下；举例service他实现某些逻辑，它有接口依赖，就应该由于能力提供方(下次层级来实现)，而不建议本层级来实现自己写的接口；

**Comment by xmgtony** [comment]
本层级是提供默认实现，并且没有对外导出。如果有多个不同版本的实现，自行实现即可。大部分接口至始至终可能只有一个实现。这里不是微服务，所以本层定义，本层实现即可。微服务的话可由使用方提供接口，服务提供方实现对应能力，或者定一个中间层。
另外对于kratos的所谓工程化不敢认同。
接口使用实际工程中很大一方面是为了测试方便。通过解耦可以提供mock相关的service实现对应接口，做一些测试数据。

有想法欢迎一起探讨哈。
