### ISSUE TITLE
绷不住了

### ISSUE THREAD

**Issue by Bronya0** [xmgtony/apiserver-gin#38]
![image](https://github.com/xmgtony/apiserver-gin/assets/55728567/51788fb6-a84c-4ce9-a521-47592b58c62b)

.变成了中文句号，ai生成完也不检查一下吗😂

**Comment by xmgtony** [comment]
您好，目前检查过主干分支和开发分支，均未发现出现中文句号的情况，可以提供下具体的版本或者commit id吗？
目前看cmd/main.go正常，在github上预览也正常，每次提交前都会启动测试的。
