### ISSUE TITLE
添加多个路由或者业务逻辑的demo

### ISSUE THREAD

**Issue by gitzh2017** [xmgtony/apiserver-gin#5]
您好，能不能加一个多个业务逻辑的demo比如role，想看下怎么添加多个业务逻辑需要怎么做

**Comment by Mustenaka** [comment]
个人觉得在internal中把 route 按照业务逻辑（实体）的方式切割成不同的组，当然这样得改一下repo和service，切割业务分文件夹，不然内容多起来挺乱的。

**Comment by xmgtony** [comment]
你好，最近较忙，后面会补充一个完整的案例。
多个业务无非是，每个业务一组自己的 repo，service，handler，router 把这几个用wire或者手动组装好即可。

wire的使用建议查看[官方教程](https://github.com/google/wire/blob/main/_tutorial/README.md)

**Comment by xmgtony** [comment]
> 

完全可以，按照自己业务需求来，没有好的布局，只有合适的布局。

目前router中可以自己定义多个router文件，比如user_router.go ,  product_router.go。分别对应自己的-->handler-->server->repo。

如果是微服务，有多个项目，internal建议拆分成子包，每个子包对应一个项目，每个包里有自己的repo，server，handler，router。

**Comment by xmgtony** [comment]
> 个人觉得在internal中把 route 按照业务逻辑（实体）的方式切割成不同的组，当然这样得改一下repo和service，切割业务分文件夹，不然内容多起来挺乱的。

完全可以，按照自己业务需求来，没有好的布局，只有合适的布局。

目前router中可以自己定义多个router文件，比如user_router.go , product_router.go。分别对应自己的-->handler-->server->repo。

如果是微服务，有多个项目，internal建议拆分成子包，每个子包对应一个项目，每个包里有自己的repo，server，handler，router。

**Comment by xmgtony** [comment]
> 个人觉得在internal中把 route 按照业务逻辑（实体）的方式切割成不同的组，当然这样得改一下repo和service，切割业务分文件夹，不然内容多起来挺乱的。

完全可以，按照自己业务需求来，没有好的布局，只有合适的布局。

目前router中可以自己定义多个router文件，比如user_router.go , product_router.go。分别对应自己的-->handler-->server->repo。

如果是微服务，有多个项目，internal建议拆分成子包，每个子包对应一个项目，每个包里有自己的repo，server，handler，router。

**Comment by gitzh2017** [comment]
如果新增product_router.go    provider_set.go里面怎么写wire比较好呢

**Comment by gitzh2017** [comment]
后面这个项目大概什么时候会更新哈，有点期待

**Comment by xmgtony** [comment]
> 

你好，最近在考虑做个小业务场景的demo。抽空我会更新下。

**Comment by xmgtony** [comment]
> 后面这个项目大概什么时候会更新哈，有点期待

你好，最近在考虑做个小业务场景的demo。抽空我会更新下。

**Comment by gitzh2017** [comment]
期待更新，我新的生产项目准备用你的 layout

**Comment by gitzh2017** [comment]
或者搞个QQ微信群也比较好沟通

**Comment by xmgtony** [comment]
> 期待更新，我新的生产项目准备用你的 layout

已更新，加了个小功能
