### ISSUE TITLE
基于您这个项目往分布式方向修改有什么建议么？

### ISSUE THREAD

**Issue by Mustenaka** [xmgtony/apiserver-gin#6]
如题，想根据您这个项目结构部署成分布式的系统后端，请问有什么建议么？

**Comment by xmgtony** [comment]
我理解的你想要的分布式后端，应该是指微服务中，提供rpc服务的服务端。微服务中涉及很多组件。该项目并未涉及，如果只是作为服务提供方，建议增加rpc相关的远程调用组件即可。
